### ISSUE TITLE
Managed Service Account Usage

### ISSUE THREAD

**Issue by aponjos** [SQL-FineBuild/Common#2] opened 2020-10-13 02:44 UTC
I'm having issues when using Managed Service Account, it keeps coming back with: " /SQLSVCPASSWORD:" is required, but service accounts does not have a password that we can set. Just putting a wrong password allows the validation to continue just to fail later on with: 

2020/10/12 22:04:59 FB1P 1E:    Setup Accounts
2020/10/12 22:04:59 FB1P 1E:    Set Buildfile value ProcessId: 1E
2020/10/12 22:04:59 FB1P 1E:    Set Buildfile value ProcessIdDesc: Setup Accounts
2020/10/12 22:04:59 FB1P 1E:    Set Buildfile value ProcessIdTime: 22:04:59
2020/10/12 22:04:59 FB1P 1ED:   Setup Kerberos
2020/10/12 22:04:59 FB1P 1ED:   Set Buildfile value ProcessId: 1ED
2020/10/12 22:04:59 FB1P 1ED:   Set Buildfile value ProcessIdDesc: Setup Kerberos
2020/10/12 22:04:59 FB1P 1ED:   Set Buildfile value ProcessIdTime: 22:04:59
2020/10/12 22:04:59 FB1P 1ED:   GetKerberosFile:
2020/10/12 22:04:59 FB1P 1ED:   SetupFolder: EUROPA\Documentation
2020/10/12 22:04:59 FB1P 1ED:   SetupFolder: EUROPA
2020/10/12 22:04:59 FB1P 1ED:   ***** Error has occurred *****
2020/10/12 22:04:59 FB1P 1ED:    Process    : 1ED: Setup Kerberos
2020/10/12 22:04:59 FB1P 1ED:    Error code : 5
2020/10/12 22:04:59 FB1P 1ED:    Source     : Microsoft VBScript runtime error
2020/10/12 22:04:59 FB1P 1ED:    Description: Invalid procedure call or argument: 'Left'
2020/10/12 22:04:59 FB1P 1ED:    Last Action: SetupFolder: EUROPA
2020/10/12 22:04:59 FB1P 1ED:    SQL Server install preparation failed
2020/10/12 22:04:59 FBCV        FBUtils Class_Initialize:
2020/10/12 22:04:59 FBCV        Process Var: CRASHID (FBConfigVar.vbs)
2020/10/12 22:04:59 FBCV        Get ProcessId where crash occurred
2020/10/12 22:05:00 FBCV        FBUtils Class_Initialize:
2020/10/12 22:05:00 FBCV        Process Var: LOGVIEW (FBConfigVar.vbs)
2020/10/12 22:05:00 FBCV        View the FineBuild log file
2020/10/12 22:05:00 FBCV        OpenFile: C:\Program Files\Microsoft SQL Server\FineBuildLogs\FineBuildInstallFULLMSSQLSERVER.txt
2020/10/12 22:05:00 **** 1ED:   FBUtils Class_Initialize:
2020/10/12 22:05:00 **** 1ED:   Set Buildfile value HKLMSQL: HKLM\SOFTWARE\Microsoft\Microsoft SQL Server\
2020/10/12 22:05:00 FBCR        Configuration Report Processing (FBConfigReport.vbs)
2020/10/12 22:05:00 FBCR        SetupReport:
2020/10/12 22:05:00 FBCR        DisplayHeader:
2020/10/12 22:05:00 FBCR        Set Buildfile value FineBuildStatus:  Install Failed
2020/10/12 22:05:00 FBCR        DisplayEnvironment:
2020/10/12 22:05:00 FBCR        DisplayMessages:
2020/10/12 22:05:00 FBCR        DisplaySetupParms:
2020/10/12 22:05:00 FBCR        DisplayRunTimeParms:
2020/10/12 22:05:00 FBCR        ReportClose:
2020/10/12 22:05:00 FBCR          Configuration Report processing Complete
2020/10/12 22:05:00 FBCV        FBUtils Class_Initialize:
2020/10/12 22:05:00 FBCV        Process Var: REPORTVIEW (FBConfigVar.vbs)
2020/10/12 22:05:00 FBCV        SetReportView:
2020/10/12 22:05:00 FBCV        FormatFolder:

I tried using a regular account but still comes with the same issue.  

I'm trying to install a SQLServer 2016 engine, using the latest script from GitHub:

 Software:  SQL FineBuild V3.5.0B1
 Server:    EUROPA
 User:      xxxxxxxxxxx
 StartDate: 2020/10/12

**Comment by EdVassie** [comment] 2020-11-19 09:24
Apologies for the overly long delay in responding.
1) Problem with gMSA account discovery
FineBuild currently detects if an account is a gMSA by looking for the attribute _msDS-GroupMSAMembership_.  New-ADServiceAccount uses the _-PrincipalsAllowedToRetrieveManagedPassword_ parameter to populate this attribute, and it should contain one or more Windows Group names.  Is it possible your gMSA accounts do not have a value in this attribute.  If so they will need to be updated to specify the group that will be able to use the account.
I will change FineBuild to look for a different attribute for gMSA discover and give an error message if msDS-GroupMSAMembership is blank.
2) Problem with creating \Documentation folder
This is caused by a bug in the _PathAutoConfig_ processing in FBConfigBuild.  This should produce a valid folder path that is used as a prefix for the _EUROPA\Documentation_ value seen in your FB log, but a bug allows an empty value to be given in some situations.  Again, this will be fixed in a future code release.

**Comment by EdVassie** [comment] 2020-11-24 19:32
Fix uploaded to Build Scripts 24Nov2020

**Closed as completed by EdVassie** 2020-11-24 19:32 UTC
Labels: bug
